# Generated by Django 3.2.4 on 2021-06-14 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='orgprofile', serialize=False, to='cuentas.user')),
                ('imagen', models.FileField(blank=True, default='default.png', null=True, upload_to='o_perfiles', verbose_name='Imagen')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de la Organización')),
                ('ruc', models.CharField(blank=True, default='9999999999', max_length=10, null=True, verbose_name='RUC')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('website', models.URLField(blank=True, max_length=300, null=True, verbose_name='Página Web')),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Organización',
                'verbose_name_plural': 'Perfiles de Organizaciones',
            },
        ),
    ]
