# Generated by Django 3.2.4 on 2021-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0003_alter_orgprofile_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='descripcion',
            field=models.CharField(max_length=800, verbose_name='Descripción'),
        ),
    ]
