# Generated by Django 3.2.4 on 2021-06-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizaciones', '0004_alter_orgprofile_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgprofile',
            name='descripcion',
            field=models.TextField(max_length=800, verbose_name='Descripción'),
        ),
    ]
