# Generated by Django 3.2.4 on 2021-06-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0006_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='cv',
            field=models.FileField(default='default.png', upload_to='u_cv'),
        ),
    ]
