# Generated by Django 3.2.4 on 2021-06-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0007_applicants_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='cp',
            field=models.FileField(default='default.png', upload_to='u_cp'),
        ),
    ]
