# Generated by Django 3.2.4 on 2021-06-25 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0009_alter_jobs_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='cv',
            field=models.FileField(default='default.png', upload_to='u_cv', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
    ]
