# Generated by Django 3.2.4 on 2021-06-25 15:09

import django.core.validators
from django.db import migrations, models
import empleos.models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0013_auto_20210625_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='cp',
            field=models.FileField(default='default.png', upload_to=empleos.models.user_directory_path_cp, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='cv',
            field=models.FileField(default='default.png', upload_to=empleos.models.user_directory_path_cv, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
    ]
