# Generated by Django 3.2.4 on 2021-06-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0014_auto_20210625_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='descripcion',
            field=models.TextField(max_length=800),
        ),
    ]
