# Generated by Django 3.2.4 on 2021-06-28 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0015_alter_jobs_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='fecha_aplicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
